name: Cherry Pick PR
on:
  pull_request:
    types:
      - closed

jobs:
  cherry_pick_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Octokit
        run: npm install @octokit/rest

      - name: Check for cherry-pick command in comments
        run: |
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN,
          });

          const comments = await octokit.issues.listComments({
            owner: process.env.GITHUB_REPOSITORY_OWNER,
            repo: process.env.GITHUB_REPOSITORY,
            issue_number: process.env.GITHUB_EVENT_PULL_NUMBER,
          });

          comments.data.forEach(comment => {
            console.log(`Comment: ${comment.body}`);
            const regex = /\/cherry-pick\s+release-(\d+\.\d+)/;
            const match = comment.body.match(regex);
            if (match) {
              console.log(`Cherry-pick to branch: release-${match[1]}`);
              return { branch: `release-${match[1]}` };
            }
          });
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Cherry Pick changes
        if: steps.check_command.outputs.branch
        run: |
          git fetch origin ${{ steps.check_command.outputs.branch }} && git checkout -b cherry-pick-branch && git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}

      - name: Push cherry-pick branch
        if: steps.check_command.outputs.branch
        run: git push origin cherry-pick-branch

      - name: Create pull request
        if: steps.check_command.outputs.branch
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.check_command.outputs.branch }}
          head: cherry-pick-branch
          title: "Cherry-pick PR: #${{ github.event.pull_request.number }}"
          body: "This is a cherry-pick of #${{ github.event.pull_request.number }}."


